version: '3.1'

services:
  web:
    image: nginx:alpine
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80